"""Human-facing attention surface: a Markdown file regenerated by integral overwrite every cycle.

It is a render of the circuit-broken FailureStore entries (the authoritative state is the FailureStore JSON
in state_dir). Never parsed back -> no markdown round-trip fragility. Lives in output_dir so the user sees it
in Obsidian. When nothing is circuit-broken, writes a single 'nothing needs attention' line.
"""
from __future__ import annotations

from pathlib import Path

_FILENAME = "_zhihu-watcher-attention.md"


def _cause_hint(url: str) -> str:
    if "zhuanlan.zhihu.com" in url:
        return ("专栏 nav-GET likely 403 from a **stale `__zse_ck`** — refresh the browser cookie via "
                "cookie-manager; if it persists after a fresh cookie, the content is unreachable.")
    return ("fetch repeatedly failed — check cookie freshness (`__zse_ck`) first, then whether the content "
            "still exists.")


def write_attention(output_dir: str, broken: list[dict]) -> str:
    path = Path(output_dir) / _FILENAME
    path.parent.mkdir(parents=True, exist_ok=True)
    if not broken:
        path.write_text("# Zhihu Watcher — attention\n\n✓ nothing needs attention\n", encoding="utf-8")
        return str(path)
    lines = ["# Zhihu Watcher — attention",
             "",
             f"{len(broken)} item(s) circuit-broke (gave up retrying). Judge the real cause and act:",
             ""]
    for e in broken:
        title = e.get("title") or e.get("key")
        lines.append(f"## [{title}]({e.get('url', '')})")
        lines.append("")
        lines.append(f"- collection: `{e.get('collection', '')}`  ·  key: `{e.get('key', '')}`  ·  "
                     f"failures: **{e.get('failures', '?')}**")
        if e.get("excerpt"):
            lines.append(f"- excerpt: {e['excerpt']}")
        lines.append(f"- probable cause: {_cause_hint(e.get('url', ''))}")
        lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)
